%%{init:{'theme':'forest'}}%%
sequenceDiagram
participant PC as レンダリング用コンピュータ
    participant O as Optitrack eSync2
    participant R as Seeed Studio XIAO nRF52840 受信用デバイス
    participant T as Seeed Studio XIAO nRF52840 送信用デバイス

    %% 初期同期
    O->>R: 立ち上がりパルス（1回）
    R->>R: カウント初期化

    %% フレーム同期（120fps）
    loop フレーム同期（120fps）
        O->>R: 撮影時同期パルス
        R->>R: カウントアップ

        %% 無線同期
        R->>T: リクエスト（カウント）
        T-->>R: ジャイロデータ（同一カウント）

        %% PCへの送信
        R-->>PC: ジャイロデータ（カウント付き）

        %% モーションデータ
        O-->>PC: モーションデータ（Optitrack）
    end